### ISSUE TITLE
Erroneous assumption that DBF files are always ISO-8859-1 encoded

### ISSUE THREAD

**Issue by tvandervorm** [gasparesganga/php-shapefile#18]
In [ShapeFile.php, line 315](https://github.com/gasparesganga/php-shapefile/blob/master/src/ShapeFile.php#L315) there's a hardcoded call to `utf8_encode()`. When the DBF file is already UTF-8 encoded, this makes a mess of Unicode characters.

For example, `Côte d'Ivoire` becomes `CÃ´te d'Ivoire` in the country files from Natural Earth (available here: https://www.naturalearthdata.com/downloads/).

The standard way of declaring encoding seems to be a CPG file which only contains the used encoding as a string, should be pretty simple to implement reading this file and only converting when necessary.

----

edit: I've been looking around your codebase a little, and see you've already added support for CPG files here https://github.com/gasparesganga/php-shapefile/commit/026bd281c93ca4723062a42613604362226abcc2, but it's not merged to master yet. I'll give using your v3dev branch a try.

**Comment by gasparesganga** [comment]
Hi! As you have already noticed, v3 supports CPG files and manual charset definition.
For personal reasons I had to put on hold all my opensource projects for a few months, but I am back on track now. I think I will be able to release v3 within a month or so.

By the way, when I firstly released this library, I complied 100% to the official ESRI specs, which required a dBase III file that in turn defined ISO-8859-1 as the only allowed charset...
Of course, during the years, different GIS software extended the standard, adding features and arbitrary stuff and that's why I'm including the support for them, but strictly speaking, doing that I am moving away from the stardard...
