### ISSUE TITLE
Empty real/double/... fields are returned as "****"

### ISSUE THREAD

**Issue by amestsantim** [gasparesganga/php-shapefile#20]
I am not sure if this is a bug or by design. Empty decimal type fields are returned as a bunch of "*"s

See attached screenshot
![Screenshot of dump of fetchRecord()](https://user-images.githubusercontent.com/8392160/65408393-d14d4300-dded-11e9-924e-f341c9ef7aca.png)

**Comment by gasparesganga** [comment]
The library returns what it reads from the shapefiles.
Since ESRI Shapefile specs are pretty old and they expect a dBase III+ data file with no `null` or `empty` support, some software started to introduce a few *non-standard* features. One of them is a kind of *simulated null values* in DBF files, obtained filling the field with asterisks `"*"` values. Of course this is not compliant with dBase III standard, nonetheless the good piece of news is that the library can handle them just fine using `Shapefile::OPTION_DBF_NULL_PADDING_CHAR` constructor option. See the [relevant documentation](https://gasparesganga.com/labs/php-shapefile/#shapefilereader__construct).

This will do:
```php
$Shapefile = new ShapefileReader('myshape.shp', [
    Shapefile::OPTION_DBF_NULL_PADDING_CHAR => '*',
]);
```

**Comment by amestsantim** [comment]
Yes, that option does take care of it. Thanks!
Although the documentation could be worded a bit better. It sounds like the Shapefile::OPTION_DBF_NULL_PADDING_CHAR option sets the character that you'd want to replace your null values where as we're actually telling it how nulls are represented in the dbf file.

**Comment by gasparesganga** [comment]
Thank you for the feedback about the documentation. Believe it or not, writing some decent documentation is the most difficult task for me! If you have any suggestion or feel like *rewriting some part of the documentation*, feel free to get in contact with me.

About this specific case though, it is exactly as you described it when using this option with **`ShapefileWriter`** class. I've just reworded the documentation to be more clear about it
