### ISSUE TITLE
I would be nice to be able to append records

### ISSUE THREAD

**Issue by pablodegrande** [gasparesganga/php-shapefile#21]
Hi. 
To support the use case where you need to create large files (e.g. in a webpage, adding records through multiple ajax-requests), it would be nice to support appending items to a shapefile.
From the API-side, it may be enough to have a $Shapefile->appendRecord($geom). 
Thanks!

pd: I add some thoughts about the requested feature....
In my opinion, it's ok for a writer to work on append mode, so I would not introduce a ShapefileAppender.  In the internal workings, I think however that it is not trivial how to avoid nasty dependencies between the reader and the writer, as probably the writer will need to initialize itself reading existing fields if one wants to append rows easily.

**Comment by gasparesganga** [comment]
Hi Pablo.
Thank you for the idea, it looks like a very useful one indeed.

My first gut feeling would be to add a kind of `OPTION_APPEND_FILES` constructor option to `ShapefileWriter`, making it effectively able to append new records to existing files.

Talking about the possible issues with it, as you mentioned a *clean* approach would take advantage of `ShapefileReader` class to read an existing file from a `ShapefileWriter` instance, effectively introducing a dependence between them. I will think about it.
Another problem that might raise is a possible exclusive file lock and concurrent access: what if a process tries to append to a file while another one is still appending to the same one? `flock` comes in handy, but I want to experiment with different scenarios.

**Comment by pablodegrande** [comment]
IMHO, locking falls outside the library scope... which would be to read and to write files in shapefile format. Concurrency is also a problem when you use plain fwrite... php is globally unaware (unfortunately) of concurrency on filesystem. I would not expect for your library to deal with it... (I know SQLite3 does, but that only proves the complexity of dealing with it....).....

**Comment by gasparesganga** [comment]
Yes, and moreover things can get worse depending on different systems and platforms used. Anyways, I'll try to experiment a bit and probably will implement some sort of *soft advisory lock*, the ultimate goal is not handling concurrent writes, but simply trying to detect them and possibly throwing an exception. It will be up to the programmer to deal with them.

Getting back to what you wrote in [this disqus comment](https://gasparesganga.com/labs/php-shapefile/#comment-4649103670) about arbitrary file seeks, that was actually one of my biggest concerns about performance. Using some memory buffers to avoid most of the seeks sounds like a reasonable idea.
Expanding on that concept of having the whole SHX file in memory, what would you think about pushing it even further, having an optional *memory only* mode that would cause the ShapefileWriter class to use only memory buffers until some dedicated method is called (ie: `writeBuffers()` or `flushBuffers()`, or something similar) or the file is closed? Some kind of *auto flush every X records* option could be a good idea too, so a programmer wouldn't have to keep track of records in case he decided to use that mode, but instead he would set a threshold and disk writes would happen just every XX records...

I am just writing down ideas here, since you have experimented extensively, you probably have a clearer understanding of where performances would be found, keeping a neat approach with the library. Of course, all of that would not preclude that *append* mode, but since I have to retouch the code, I'd better to everything at once.

**Comment by pablodegrande** [comment]
The 'all-in-memory' option in amazingly easy to implement by opening the files as php://memory stream. However that option create the whole file in memory, not by chunks (unless you close the memory stream, flushit and reopen it)

**Comment by gasparesganga** [comment]
What I had in mind was more something like a writing buffer. Instead of immediately writing data to open streams, using some buffers and write data to the actual streams periodically or when a specific method is called.
I will investigate that, because on one hand I know there is a big margin for performance optimization within the library, but on the other the one of the whole v3 rewrite targets was to have some *elegant and readable code*, even at the cost of some performances.

**Comment by pablodegrande** [comment]
I think elegant and readable is a worthy design goal. Enough to put it before everything else. You may stop performance optimization where they render code more complicated. Related to that:
1) too many buffers may be enoying to read and debug.
2) fseeking backward lessens readability. maybe that could change. or not =)
3) yesterday I tried this, that makes code more compact, and reduces encodeFieldValue to 1/4 of required time...
			$value = floatval($value);
			$value = number_format($value, $decimals, '.', '');
instead of:
                    $value          = trim($value);
                    $flag_negative  = substr($value, 0, 1) === '-';
                    $intpart        = $this->sanitizeNumber(strpos($value, '.') === false ? $value : strstr($value, '.', true));
                    $decpart        = $this->sanitizeNumber(substr(strstr($value, '.', false), 1));
                    $decpart        = strlen($decpart) > $decimals ? substr($decpart, 0, $decimals) : str_pad($decpart, $decimals, '0', STR_PAD_RIGHT);
                    $value          = ($flag_negative ? '-' : '') . $intpart . ($decimals > 0 ? '.' : '') . $decpart;
floatval goes instead of sanitizeNumber...

**Comment by gasparesganga** [comment]
Yay, I'm on the same boat, that's why I wanted to think it thoroughly before jumping on the *buffer everything* ship :)
Anyways, I will definitely try to do something about that fseeking if possible.

About the float parsing code, I know `floatval()` would drastically improve performances, but that would prevent *huuuuuuuuuuuuuuuuuuuge* numbers to be parsed correctly (also, there could have been other reasons related to poor dBase format, but I forget them now). Double precision should be enough for any reasonable use, but trust me when I tell you that in many years dealing with shapefiles I have seen the most unimaginable things, included 100+ digits numbers (they are stored as text anyways in DBF files). What I can do anyways, is checking whether native floating point PHP functions don't overflow and eventually use the string-based approach just in weird cases, that should boost the performances.

**Comment by pablodegrande** [comment]
Yes, you could check if the provided argument is of numeric type (is_float | is_int). That would simplify things, and you could use your existing code for strings...

**Comment by gasparesganga** [comment]
I have been running some tests and my conclusions are pretty much the same that had led me to use a custom sanitization function based on strings: using some `floatval()` and `number_format()` in `ShapefileWriter::encodeFieldValue()` function brings a tiny performance boost, which becomes evident only in a particular case, when meny floating point fields are defined, while at the same time geometries are fairly simple ones (a condition rarely met in the average shapefile).

On the other hand, it tighteens floating point precision to the machine and some unexpected results and roundings/overflows may occur with large numbers or the ones that requires a very high precision. Unfortunately dBase format stores everything as text and many datasets are exploiting that to store ridicoulus numbers (imagine some 20+ digits codes that are best suited for a *char* field, but are stored as *numbers* instead...).
Add to that that `is_float()` and `is_int()` cannot be used to decide what encoding strategy is better to use, for the very same reasons as `floatval()` and `number_format()` would fail.
It is true users should pass a ***number*** to a numeric field, but in accordance with dBase, where everything is stored as text, it does make sense to accept a *string encoded number* as a valid value.

Bottom-line, I don't think it is worth doing anything within that `ShapefileWriter::encodeFieldValue()` fucntion.
A particular dataset might suffer from poor performances (e.g.: simple geometries and lots of numeric data), but for the average dataset it won't be an issue at all. Plus, I prefer to have a 100% reliable encoding that won't alter my input data, even in the worst corner cases.
Well, that's just my opinion.

Going back to the main topic, file append will be included, that's for sure!

**Comment by pablodegrande** [comment]
It's your call... but numbers tell, in my tests, that you would be reducing performance of the fragment between 300% and 400%. 

TEST->input: 1234.123
ellapsed format 2: 438.91000747681 secs
ellapsed format: 1817.8880214691 secs

TEST->input: 1234
ellapsed format 2: 483.25395584106 secs
ellapsed format: 1425.1148700714 secs

$starttime = microtime(true);
$input = 1234.123;
for($n = 1; $n < 100000; $n++)
	$q = format2(10, 2, $input);

echo 'ellapsed format2: ' . 1000 * (microtime(true) - $starttime) . ' secs<br>';
$starttime = microtime(true);

for($n = 1; $n < 100000; $n++)
	$q = format(10, 2, $input);

echo 'ellapsed format: ' . 1000 * (microtime(true) - $starttime) . ' secs<br>';
exit;


function format2($size, $decimals, $value)
{
     if (!is_float($value) && !is_int($value))
		return format($size, $decimals, $value);

	$value = floatval($value);
	$value = number_format($value, $decimals, '.', '');
	if (strlen($value) > $size) {
		throw new \Exception();
	}
	$value = str_pad($value, $size, 'x', STR_PAD_LEFT);
  return $value;
}

function format($size, $decimals, $value)
{
  if ($value !== null) {
		$value          = trim($value);
		$flag_negative  = substr($value, 0, 1) === '-';
		$intpart        = sanitizeNumber(strpos($value, '.') === false ? $value : strstr($value, '.', true));
		$decpart        = sanitizeNumber(substr(strstr($value, '.', false), 1));
		$decpart        = strlen($decpart) > $decimals ? substr($decpart, 0, $decimals) : str_pad($decpart, $decimals, '0', STR_PAD_RIGHT);
		$value          = ($flag_negative ? '-' : '') . $intpart . ($decimals > 0 ? '.' : '') . $decpart;
		if (strlen($value) > $size) {
			throw new \Exception();
		}
		$value = str_pad($value, $size, 'x', STR_PAD_LEFT);
  }
	return $value;
}

**Comment by gasparesganga** [comment]
I performed some similar tests and your results are spot on: performances are 3 or 4 times better using PHP built-in functions, but those results don't take into account everything else I wrote before.

Of course if you use as reference a shapefile with simple geometries (points, or linestring/polygons with a few points each) and many numeric fields, execution time gets shifted toward number  DBF encoding.
But on a typical and average shapefile, this encoding function accounts for a very tiny fraction of execution time. Try yourself with some complex geometries or even with simple points but without tens of numeric fields. 

Even if I wanted to address some special use cases like that, what really worries me is the unwanted rounding that might happen: have you tried encoding something like that: `"1234567890123456789.123456789"`?
There are so many legacy shapefiles relying on text representation of large numbers, I don't want to break the functionality for them.

**Comment by pablodegrande** [comment]
My profiling was made on a balanced geometry vs. data shapefile (dbf was 2.6MB and .shp was 1.4MB (for 5k rows)). In that scenario, 20% of total time was consumed in this function. About large numbers, it would be enough to check if they are strings. 

But again, it's your call. And most important: the library works as expected, and it's a data transformation library.... performance should not be driving design nor taking much of your time.

**Comment by gasparesganga** [comment]
Don't get me wrong, I appreciate every single moment that you are dedicating to this library, really!
I am getting some great feedback and it will help the library to improve, so any input is more than welcome.

There must be something fundamentally different between your profiling and my tests then: with hundreds of real world shapefiles from my archive, I have never reached a significant improvement in execution time changing that function (just to give some numbers: an average improvement of 1sec over a 30secs total for 20k records in 20 iterations). The only case where that  in a specific case with simple geometries and many numeric fields.
Feel free to send me your example data if you want (I assumed it was the one you already sent me by email), no problem.

PS: You have just stated an obvious thing that I had failed to think about (talk about overcomplicating things...): using my string-based encoding only if a ***string*** is passed to the function, otherwise, welcome `number_format(floatval($value), $decimals, '.', '')`!
That will probably do, great! ;)
