### ISSUE TITLE
Sanitize and repeated names

### ISSUE THREAD

**Issue by pablodegrande** [gasparesganga/php-shapefile#23]
Hi. 
I paste here the code I used to avoid naming conflicts derived from trimming field names.  You should change the function variableExists to iterate your internal collection of field names... I used these functions from outside the component... they are not very elegant, but they did the job.

Regards, Pablo.

	private function fixVarName($name, $cols)
	{
		$n = 0;
		$name = strtoupper($name);
		$nCandidate = $candidate = $this->sanitizeDBFFieldName($name);
		while($this->variableExists($nCandidate, $cols))
		{
			$n++;
			$nCandidate = $this->appendNumber($candidate, $n);
		}
		return $nCandidate;
	}

	private function variableExists($cad, $cols)
       {
		foreach($cols as $col)
			if (isset($col['effectiveVariable']) && $col['effectiveVariable'] === $cad)
				return true;	
		return false;
	}

	private function appendNumber($cad, $n)
       {
		$futureLength = strlen($cad . '_' . $n);
		if ($futureLength > 10)
			$cad = substr($cad, 0, strlen($cad) - ($futureLength - 10));
		return $cad . '_' . $n;
       }

**Comment by gasparesganga** [comment]
What approach would you use to implement this?

1) Making `$flag_sanitize_name` in field-adding methods (`ShapefileWriter::addField`, `ShapefileWriter::addCharField`, `ShapefileWriter::addNumericField`, etc.) ***always*** using a similar logic, so that conflicting names would be converted into `XXXXXXX_01`, `XXXXXXX_02`, etc.?

2) Converting `$flag_sanitize_name` parameter from a boolean flag to an enum one:
```
- Shapefile::SANITIZE_NAME_NONE - No sanitization (current false value)
- Shapefile::SANITIZE_NAME_SIMPLE - Uppercase and replace invalid chars (current true value)
- Shapefile::SANITIZE_NAME_NOCONFLICT - Uppercase, replace invalid chars and avoid name conflicts with other fields appending _01, _02, _03, etc.
```
3) Leaving `$flag_sanitize_name` a boolean one but adding a constructor option (e.g.: `Shapefile::OPTION_DBF_SANITIZATION_NOCONFLICT`) that will cause the flag to act either like a *simple* sanitization (as is now) or a conflict-resolving one.

**Comment by pablodegrande** [comment]
I guess I would go for option 1., as I cannot a imagine a scenario where you want the function to trim long names, but leave conflicting results alive...

**Comment by gasparesganga** [comment]
I was thinking about some special situation where a programmer would like to deal with conflicts with a custom function, but in the end this is something that he could carry out *before* even passing the field names to the library. And besides that, comparing the original field name with the one returned by library methods will still be an effective way to determine whether a name was *valid* or not.

I will probably go with option 1 indeed, leaving an eventual possibility for option 3 to be implemented in the future if someone raises a valid use case.
