### ISSUE TITLE
unpack(): Type d: not enough input, need 8, have 0 

### ISSUE THREAD

**Issue by Kocicak** [gasparesganga/php-shapefile#26]
Hello, I have problem with reading shapefile. It contains 1805 entries and first 1804 are fine, but the last one gives me error:

unpack(): Type d: not enough input, need 8, have 0 in /var/www/html/vendor/gasparesganga/php-shapefile/src/Shapefile/ShapefileReader.php:272

I am attaching a file that gives error: [exmample.zip](https://github.com/gasparesganga/php-shapefile/files/4214005/exmample.zip)

I am reading file with code:

```
$shapefile = new ShapefileReader(
    $file->getRealPath(), [
        Shapefile::OPTION_ENFORCE_POLYGON_CLOSED_RINGS => false,
    ]
);

try {
    foreach($shapefile as $i => $geometry) {
        var_dump($i);
    }
} catch (ShapefileException $e) {
    var_dump($e->getMessage());
    break;
}
```

Can you please help me? I don't know what is wrong with that file. It gives me "polygon has open rings" error, but geometry checker in qgis says it is ok. After supressing that error, is gives th unpack() error. Thank you.

EDIT: I have managed to bypass "Polygons cannot contain open rings" error by setting OPTION_SUPPRESS_M and OPTION_SUPPRESS_Z options. But unpack error still happens.

EDIT2: Replacing last line in ShapeFileReader::readDoubleL method with `return @current(@unpack('d', $ret));` (added `@` marks) results with all geometries is read correctly without error. Maybe there is some error with reading to the end of file?

**Comment by gasparesganga** [comment]
I'll give a look at that file, but my *gut feeling* is that the file is corrupted (not so unusual with shapefiles created with 3rd party software) and it's missing some bytes at the end...

I don't think suppressing a potential fatal error is the right choice by any means.... 
You wrote QGIS can open the file, but are you sure it isn't simply ignoring that polygon with open rings? How many geometries does it fetch from the shapefile?

**Comment by gasparesganga** [comment]
I inspected your file and it is corrupted indeed.
- `Shapefile::ERR_GEOM_POLYGON_OPEN_RING` error is triggered by M dimensions, they seem to be absolutely off! First and last point of a polygon ring must be the same, but in this file their M coordinates are different (X and Y are the same though and Z is always 0). If you set `Shapefile::OPTION_SUPPRESS_M` option the error will disappear because M dimensions won't be checked for integrity.
- The SHP file is incomplete and bytes that are missing are *M range* (bounding box) and *M array* (coordinates) of the last polygon ring. QGIS does not complain because it simply ignores M dimension, but this is a wrong and potentially dangerous behaviour in my opinion.

It seems to be exported by QGIS, what version are you using? If it's the latest, you could fill a bug report to its developers...

If you want to *sanitize* the shapefile, my advice is using my library to read the shapefile and write it to a new one, suppressing M (and Z too if you don't need it) dimensions. For this process you will use both `ShapefileReader` and `ShapefileWriter` classes at the same time and you can safely ignore those PHP Warnings: it's going to be a one-off operation.

After you have saved a new shapefile using this library, no warning will be raised as there won't be any missing bytes, I promise :)

**Comment by Kocicak** [comment]
I thought it is the shapefile problem. I don't need M and Z dimensions, so I will sanitize the shapefile. Thank you
