### ISSUE TITLE
Typehints are a bit off

### ISSUE THREAD

**Issue by ChristianAdamski** [gasparesganga/php-shapefile#28]
Hey,

I use your library on a submodule dependency here: https://www.drupal.org/project/geolocation, so thanks a lot for oyur work!

That being said, the code documentation, or typehint or what you call that, is a bit off on v3.

The ShapefileReader::fetchRecord for example just states a return of "Geometry" instead of the fully named "\Shapefile\Geometry\Geometry" as required by PHPStorm and others.
Also, the abstract Geometry::getGeoJSON() states no default values for the parameters. where every implementation uses some, so the paramters are not required. PHPStorm will mark my code as broken, as I'm missing those parameters, even though they will always be set.

I should provide a patch here, but I'm not sure, if I can find the time soon...

**Comment by gasparesganga** [comment]
Hi Christian, thank you for your feedback (and great project you got there!)
I am currently working on v3.3.0 release, so it's a perfect time to include some tiny embellishments as you suggest.

First of all, I think we can agree that those PHPDoc comments are ugly, difficult to maintain and introduce a great deal of chances for inconsistencies between the real code and its *documentaion*. It's true that with PHP 7, real type hinting and other modern features, most of them are absolutely redundant, but unfortunately I want to support PHP 5.4+ and this comes with some stylistic tradeoffs. As soon as PHP 5.4 is not relevant anymore, I will scrapt them of in favour of some decent PHP 7+ code (still a long way to go IMHO, RHEL actively supports and security patches it...)!

On the other hand, I personally dislike those IDEs that tend to *force* the programmer maybe way too much into some stylistic assumptions, without offering some flexibility to customize things here and there, but this is not the right place to discuss that (I am a die-hard old school dinosaur, so Notepad++ and a couple of plugins go a long way as a IDE for any language and environment for me...).

Anyways, I will push a commit to fix those PHPDoc comments soon, no need to provide a patch, it's pretty trivial to fix. Are you aware of other errors or are those you already pointed out the only one you could find?

Thank you

**Comment by ChristianAdamski** [comment]
I'm still working on this. So I can't say with certainty yet, but I think this is it.

**Comment by ChristianAdamski** [comment]
Just FYI: I had a weak dependency before, but that caused issues for sometimes getting v2 and sometimes v3 because of the sloppy composer setup. I'm bringing this in order right now, enforcing v3, but have to alter my code to reflect that.

**Comment by gasparesganga** [comment]
Could you elaborate better on this latest issue please (composer)? I'm not sure I'm getting it right...


I've just had a look at the code and it seems your IDE should complain about `MultiPoint::addPoint()` too, since PHPDoc comments speficy a `Point` parameter without including the fully namespaced qualified name... The only difference is that class `MultiPoint` is in the same namespace as `Point`... Or maybe it's relying on the object type hint, which is allowed in PHP 5.4: method definition is `public function addPoint(Point $Point)`.
Could you check your IDE behaviour when you drop the type hint from method definition and it has to rely exclusively on PHPDoc comments, and give me some feedback please?

About that abstract `Geometry::getGeoJSON()`, there is a number of ways to normalize it but the easiest one seems to be defining a default value for the parameters in the abstract method signature in `\Geometry\Geometry`: `abstract public function getGeoJSON($flag_bbox = true, $flag_feature = false)`. PHP does not complain about this of course, but does your IDE?

**Comment by ChristianAdamski** [comment]
Ignore my composer comment. I did stuff wrong on my end.

The addPoint() function and others don't matter to me right now, as I'm using this library purely to read shapefiles, so I simply wouldn't notive PHPStorm complaining. Might change in the future of course, but not right now. I would argue that if nobody stepped up writing an issue, how bad can it be?

Your approach to altering getGeoJSON is perfectly fine for me. I don't know about PHP 5.4. I know RedHat still supports that, but boy is that outdated by now. So I sadly can't help you there.

**Comment by gasparesganga** [comment]
Well, even if you are not using `Geometry::addPoint()` explicitly, the library under the hoods is using it to read shapefiles, a lot. Even if some things don't matter to you right now, they might in the future since you are using this library in a project. I think it's for everybody's interest that we try to come up with the best and most complete solution, since this is strictly related to the issue you mentioned and that I am willing to fix.

I asked for some feedback, as I don't use PHPStorm and don't have access to a fully fledged IDE right now. Could you kindly confirm that PHPStorm:
1. Does not complain if you change `MultiPoint::addPoint()` definition to `public function addPoint($Point)`
2. Change that abstract `Geometry::getGeoJSON()` signature as I suggested before?
Thank you.

<br>

> *I would argue that if nobody stepped up writing an issue, how bad can it be?*

As I wrote in my first reply, we're talking about embellishments here, PHPDoc-style comments to help IDEs and programmers understanding what's going on without using PHP 7+ features that are not compatible with earlier versions. The code actually works fine, so I'd say it's definitely not so bad... but I understand it might be annoying to have your IDE complaining about something, that's why I'm all in to fix this.

**Comment by ChristianAdamski** [comment]
I just tried your scenario. If I typehint to MultiPoint and call addPoint(), PHPStorm correctly complains about requiring a Poin obejct. See screenshot

![PHPStorm](https://user-images.githubusercontent.com/8464825/80982432-9a331b80-8e2b-11ea-8928-1f6ba441f512.png)

**Comment by gasparesganga** [comment]
Great, thank you!

I am currently working on other features and will push a commit to address this issue after that.
In the meanwhile if you find anything else, get back to me of course.

**Comment by ChristianAdamski** [comment]
No no, thank you :)

If I find something, I'll add it here.

**Comment by gasparesganga** [comment]
I've just pushed some commits that address this issue.
There were many other similar cases that should be fixed now.

Would you like to perform some checks with your IDE on the master branch before I release v3.3.0? I'm still updating the documentation and write some release notes, so you got time to request more fixes before it gets released ;)

**Comment by ChristianAdamski** [comment]
Sorry for the delay, things and schedules are weird right now.

Th changes are enough to make my PHPStorm happy, but my usecase is very trivial. If I should happen to get to something more sophisticated, I'll happily report back :)
