### ISSUE TITLE
Write new SHP file: Fatal error: Uncaught Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by patrickbussmann** [gasparesganga/php-shapefile#31]
I wrote a small SHP file creation script and got an error.
After debugging I found out that the error is directly at the beginning.

```php
$filename = tempnam(sys_get_temp_dir(), 'shp') . '.shp';
$shp = new ShapefileWriter($filename);
$shp->setShapeType(Shapefile::SHAPE_TYPE_POLYGON);
$shp->addCharField('ID', 36);
$shp->addCharField('DESC');
```

```
Fatal error: Uncaught Trying to access array offset on value of type null

\vendor\gasparesganga\php-shapefile\src\Shapefile\ShapefileWriter.php:588
\vendor\gasparesganga\php-shapefile\src\Shapefile\ShapefileWriter.php:1059
\vendor\gasparesganga\php-shapefile\src\Shapefile\ShapefileWriter.php:184

  thrown in vendor\gasparesganga\php-shapefile\src\Shapefile\ShapefileWriter.php on line 588
```

Thanks in Advance for solutions.

**Comment by gasparesganga** [comment]
The code you posted here, even if it doesn't make much sense on its own (it produces an empty shapefile!) does seem to execute just fine.
Can you provide the actual code that is raising the error?

**Comment by patrickbussmann** [comment]
Yes @gasparesganga here is an example.

    $ composer require gasparesganga/php-shapefile

Then you have this file.

```php
<?php

require_once 'vendor/autoload.php';

use Shapefile\Shapefile;
use Shapefile\ShapefileWriter;

$filename = tempnam(sys_get_temp_dir(), 'shp') . '.shp';
$shp = new ShapefileWriter($filename);
$shp->setShapeType(Shapefile::SHAPE_TYPE_POLYGON);
$shp->addCharField('ID', 36);
$shp->addCharField('DESC');
```

Error!

PHP 7.4 - maybe thats the issue?

**Comment by gasparesganga** [comment]
Alright got it. I was testing it with a different PHP version.
It's happening due to the *empty shapefile*: there's no defined *bounding box*.

Now, that's more of a conceptual problem rather than a technical one. The specs state about empty shapefiles (emphasis is mine):

> If the shapefile is empty (that is, has no records), the values for Xmin, Ymin, Xmax, and Ymax are ***unspecified***.
> Mmin and Mmax can contain "nodata" values for shapefiles of measured shape types that contain no measures.

 One could argue that a shapefile *should* have at least one record/geometry by definition... I could enforce that, or leave it as is and allow the creation of an *empty shapefile*, but I should define some kind of default value for the bounding box.

Candidates values might be:
1. All min and max values set to `0` (ugly and very different than *unspecified*).
2. All min values set to the highest allowed number and all max values set to the lowest one.

I'd go with the second option, because it would ensure that when opening that file again and appending records to it, the bouding box would be computed correctly according to the newly added geometries (that would **NOT** be the case setting all values to `0`).

<br>
I'm thinking about it and will soon release a bugfix.

In the meanwhile, can I ask you why do you need an empty shapefile, in the first place? :)

**Comment by patrickbussmann** [comment]
yes @gasparesganga you can 🙂

I have a Google Maps frame with the toolbox enabled. The users can draw a polygon in there. And then they should be able to export this polygon to different formats.

At the moment I support KML, XML and GeoJSON.
And with your library I want to export to SHP, too.
That's why it's empty.

**Comment by gasparesganga** [comment]
Great project and props for the multi-format export. People tend to *mistreat* shapefiles but more often than not they ultimately fall back to them when it comes to interchanging among different software ;)

Don't worry about this small bug, I'm working on it and I'm taking the chance to introduce a bigger change too (faster and simplier polygons orientation detection). I'll release a new version soon.

**Comment by gasparesganga** [comment]
It turned out to be a trivial fix. I cannot run too many tests right now, as I am currently off-site, but I'm pretty confident this last commit has fixed any possible issue with *unspecified* bounding boxes when writing shapefiles headers.
Feel free to test this patch using the source files and provide feedback, before I publish a new release that will require a few more commits to address those other things I mentioned.

I decided to use a *negative no-data value* (which becomes positive!) for `xmin` and `ymin`, and regular one for `xmax` and `ymax`.
They are some sufficiently high and low values, they make some sense in the shapefile context as they are already being used for *no-data* M coordinates and most importantly this should ensure a correct behaviour when any geometry is appended to an existing shapefile opened using`Shapefile::OPTION_EXISTING_FILES_MODE  => Shapefile::MODE_APPEND` option.
