### ISSUE TITLE
Shapefile Will Not Load Correctly

### ISSUE THREAD

**Issue by ibanks** [gasparesganga/php-shapefile#35]
Hello. I am running into an issue where I provide the path of the .shp file to load into the parser and for some reason it is returning an error. 

`
"Error Type: ERR_FILE_EXISTS
Message: Check if the file exists and is readable and/or writable
Details: .../project/public/storage/cb_2019_us_tract_500k.shx"
`

What is odd about this error is that it seems to be looking for a .shx file instead of .shp. Please advise. Thanks so much

**Comment by gasparesganga** [comment]
A *complete* Shapefile is composed *at least* of 3 different files: SHP, SHX and DBF.
Don't you have `cb_2019_us_tract_500k.shx` and `cb_2019_us_tract_500k.dbf` files too?

In case you don't, there are some options (`Shapefile::Shapefile::OPTION_IGNORE_FILE_DBF` and `Shapefile::Shapefile::OPTION_IGNORE_FILE_SHX`) that will allow you to read just the SHP file, but bear in mind that such it would be considered as a ***corrupted*** Shapefile and of course no data will be available for the geometries... Use them only as the very last resort when you have absolutely no access to either SHX or DBF file and want to recover at least the geometries from an invalid Shapefile...

**Comment by ibanks** [comment]
@gasparesganga 

> A complete Shapefile is composed at least of 3 different files: SHP, SHX and DBF.

This is what I needed to know. I'm new to this technology as my goal is to be able to extract the geometry and display zones on Google Maps. Thank you so much for your responsiveness!

To further answer your questions, yes I have all of the files as they were downloaded from the Census Bureau. I believe I now have to find a way to compile them into one shapefile.

**Comment by ibanks** [comment]
@gasparesganga Does your tool read from a zip file?

**Comment by ibanks** [comment]
@gasparesganga I believe I may have figured it out. I created an upload file tool which uploads a file and executes your script individually. What I see is that all 3 files need to be present before your script is executed. I did this and the shapefile object was created.

**Comment by gasparesganga** [comment]
Yes, that would be the right approach, either uploading a zip/tar/gzip file or uploading multiple files that compose the Shapefile archive (eg: PRJ and CPG file). Take a special care about the CPG file, because there are many shapefiles out there encoded in `UTF-8` or charsets different than `ISO-8859-1` and since this is actually *not in the specs*, the CPG file is fundamental to instruct the library about it.

If you are new to Shapefiles, the [Wikipedia page](https://en.wikipedia.org/wiki/Shapefile) is a quick good read.

I think you have already figured it out, but to extract a zip archive you can use PHP [ZipArchive ](https://www.php.net/manual/en/book.zip.php) or an external library. It's out of the scope of my library.
