### ISSUE TITLE
Shrinking The Coordinates

### ISSUE THREAD

**Issue by ibanks** [gasparesganga/php-shapefile#36]
@gasparesganga Is there a way through your tool to shrink the polygon points? For instance, if you have polygon geometry with 300 points, is there a way to reduce the points down to 5? The purpose of this is to display the resulting polygon using Google Maps and they have a polygon point limit.

Edit: Does getBoundingBox() do this?

**Comment by gasparesganga** [comment]
First things first: I think the [comments](https://gasparesganga.com/labs/php-shapefile/#comments-and-ideas) section in the official documentation page would be a more *appropriate* place to ask such a question, which is, indeed, a *question* and not an *issue*. I don't want to be picky here, but there is a broader audience of users that might profit from a question asked in the official documentation page, while not so many check closed issues on github.

About your questions:

> Is there a way through your tool to shrink the polygon points?

No, there isn't. That would be out of the scope of this library, that is *reading and writing shapefiles*. For geometric and topological processing there are other libraries out there, some of which offer some *simplifying* algorithms. Said that, I doubt that it would be possible to simplify a 300-points polygon into a rectangle without loosing completely its topology.
Probably you are looking for the polygon *bounding box*.


> Does getBoundingBox() do this?

`Geometry::getBoundingBox()` method returns a Geometry bounding box, that is, the *smallest box (usually a rectangle) that encloses a geometry or a set of geometries* (see also [Wikipedia](https://en.wikipedia.org/wiki/Minimum_bounding_box)).
If you need to restrict your input to 5 points, this means you are probably looking for a bounding box! Yay! ;)
(don't forget that a rectangle has 5 points, because its boundary is a *closed ring*, where the first and last points are equal).

**Comment by ibanks** [comment]
@gasparesganga Thanks again. I wasn't aware of the comments section in the documentation. I will definitely use that from now on. I also found a library to minimize the points without loosing topology. Your the combination of your tool with the library PHPGeo is game changing. It looks like I have everything working now. Thanks again.

**Comment by gasparesganga** [comment]
I'm glad you found a solution.
Cheers
