### ISSUE TITLE
Shapefile with MultiPointZ geometries

### ISSUE THREAD

**Issue by vincenzobologna** [gasparesganga/php-shapefile#39]
Hello,

first of all, it's a great package for write and read shapefiles. I'm using it in a Laravel GIS project.
My issues it's about create a Shape file with a series of a MultiPointZ geometries.

Here some lines to explain my code:

```
...
$Shapefile->setShapeType(Shapefile::SHAPE_TYPE_MULTIPOINTZ);
...
$multipoint = new MultiPoint();
$multipoint->addPoint(new Point(x, y, z));
$multipoint->addPoint(new Point(x, y, z));
...
$Shapefile->writeRecord($multipoint);
...
```

When i execute it i got this error:

_Error Type: ERR_SHP_GEOMETRY_TYPE_NOT_COMPATIBLE Message: Geometry type must be compatible with Shapefile shape type Details: 18 - MultiPointZ_

I didn't understand why and where i make a mistake.
Can you help me?
thanks a lot in advance.

**Comment by gasparesganga** [comment]
Hi!
Maybe the error message is somewhat *cryptic* (I'm not the best when it comes to writing meaningful error messages) but it is actually trying to tell you what's wrong with your code: simply put you are trying to add a *PointZ* **without an M dimension** to a *MultiPointZ* that is actually expecting one.

Shapefile specs require both Z and M dimension for **Z geometries*, thus the library is enforcing this unless otherwise instructed (see solution n.2 below). I wouldn't have done so, but hey, I'm no ESRI engineer... ;)

There are 2 possible solutions and both of them are trivial:

**1)** Specify a value for M dimension in your `Point` constructors (it defaults to `null`, any value other that `null` will do).
```php
$multipoint->addPoint(new Point(x, y, z, m));
```

**2)** Set flag `Shapefile::OPTION_SUPPRESS_M` to `true` in your `ShapefileWriter` constructor.
```php
$Shapefile = new ShapefileWriter('path/to/your/file', [
    Shapefile::OPTION_SUPPRESS_M => true,
]);
```

As a personal advice, I would go with the **second** option, much cleaner and logical if your geometries have actually no M dimension.

<br>
PS: É giusto che le risposte siano in inglese in modo che chiunque abbia un problema simile possa trovare la soluzione, ma se preferisci aggiungere qualche dettaglio in italiano non può che farmi piacere, non si lamenterà nessuno ;)<br>
In bocca al lupo per il tuo progetto, se dovessi aver bisogno di supporto, scrivimi pure senza problemi, anche via email.

**Comment by vincenzobologna** [comment]
Hello,

thanks a lot for your tips. I tried both solutions, but it still gave me the same error:
I suppose there is an issue on those lines:

```php
$Shapefile->setShapeType(Shapefile::SHAPE_TYPE_MULTIPOINTZ);
...
$multipoint = new MultiPoint();

```
No errors if I change Shape type to SHAPE_TYPE_MULTIPOINT, but I would lose Z dimensions.
Mabye I have to setup MultiPoint in another way before add Point with Z to it?

PS: grazie mille per il supporto! Sto realizzando un software per gestire i dati del sottosuolo per realizzare dei DTM, e ho bisogno di esportare in shapefile gruppi di essi per poterli lavorare su ArcGIS. qualche suggerimento su come procedere?

**Comment by gasparesganga** [comment]
Then there must be some other issue with your code somewhere else. I can guarantee both those solutions work flawlessly :)

Geometry types in the library (such as `MultiPoint`) are automatically defined as Z and/or M ones when you initialize them, in your case, with your first `$MultiPoint->addPoint()` call.
`$Shapefile->writeRecord()` then checks and enforces dimensions coherence.

Here you are a complete snippet to test it:
```php
$Shapefile = new ShapefileWriter('path/to/your/file', [
    Shapefile::OPTION_SUPPRESS_M => true,
]);
$Shapefile->setShapeType(Shapefile::SHAPE_TYPE_MULTIPOINTZ);

$MultiPoint = new MultiPoint();
$MultiPoint->addPoint(new Point(1, 2, 3));
$MultiPoint->addPoint(new Point(4, 5, 6));
$Shapefile->writeRecord($MultiPoint);

$Shapefile = null;
```

<br>

PS: É un piacere. Questa libreria negli anni è diventata la libreria di riferimento in PHP per interagire con gli Shapefiles, e questo non sarebbe stato possibile senza il feedback di tantissimi utenti da tutto il mondo che la utilizzano per i progetti più disparati e *insospettabili* (se ti nominassi Correios, ovvero le Poste brasiliane?). Senza il feedback degli utenti sarebbe rimasta la stessa di 10 anni fa, quando la creai per l'azienda dove lavoravo e andava (e va) bene così :)

Riguardo il tuo progetto, beh, messa così non posso dirti molto, ma se non hai particolari problemi con la mole di dati e le limitazioni al rispetto degli shapefiles, direi che sei sulla buona strada, alla fine gli Shapefiles oggi sono esattamente questo: un *formato di interscambio*.

**Comment by vincenzobologna** [comment]
Ok i resolved. It was just a typing error in my code on Point instantiation.

Thanks for all for now, and thanks again for support and your great library!
