### ISSUE TITLE
error when hosting - Error Type: ERR_FILE_EXISTS

### ISSUE THREAD

**Issue by ctw28** [gasparesganga/php-shapefile#41]
hi, can you help me?
when i'm on localhost there is no problem, but when i upload on hosting i get error

Error Type: ERR_FILE_EXISTS Message: Check if the file exists and is readable and/or writable Details: https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shp

the path of file is correct, what should i do?

thanks

**Comment by gasparesganga** [comment]
This happens because the library tries to check whether provided files are readable/writable using `is_readable()`, `is_writable()` and `is_file()`, expecting a filesystem file.
HTTP protocol wrapper in PHP does not support `stat()`, necessary to perform these checks. See [this](https://www.php.net/manual/en/wrappers.http.php)

You can overcome this by opening some stream resources yourself and passing them to the Shapefile constructor. See [Files and filenames](https://gasparesganga.com/labs/php-shapefile/#files-and-filenames) section in the official documentation.

Also, next release (v3.5) will include a `File` interface, allowing you to write your own implementation, abstracting the whole URL opening process even more.
The interface has already been committed, you can check it out [here](https://github.com/gasparesganga/php-shapefile/blob/b8626f26f2c6da1d1f7860842ed3b48f508cc3e4/src/Shapefile/File/File.php).

**Comment by ctw28** [comment]
thanks for your explanation.

but when i try to opening stream resources by myself, like this
$Shapefile = new ShapefileReader([
  Shapefile::FILE_SHP => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shp',
  Shapefile::FILE_SHX => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shx',
  Shapefile::FILE_DBF => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.dbf',
]);
but i still get same error...

and then i try like this

$Shapefile = new ShapefileReader([
    Shapefile::FILE_SHP => fopen('https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shp', 'rb'),
    Shapefile::FILE_SHX => fopen('https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shx', 'rb'),
    Shapefile::FILE_DBF => fopen('https://sitaru.id/peta-upload/garis-pantai/garis-pantai.dbf', 'rb'),
]);

i got error "fseek(): stream does not support seeking"

whats wrong?

**Comment by gasparesganga** [comment]
You are **NOT** opening stream resources this way:
```php
$Shapefile = new ShapefileReader([
    Shapefile::FILE_SHP => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shp',
    Shapefile::FILE_SHX => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.shx',
    Shapefile::FILE_DBF => 'https://sitaru.id/peta-upload/garis-pantai/garis-pantai.dbf',
]);
```
Rather you are simply specifying the individual files.

With the second snippet you are actually opening some resource handles, but PHP complains about the inability to perform a `fseek()` on remote resources.

I see 2 possible solutions:

1. Download a local temporary copy of these files before opening them (you can use [cURL()](https://www.php.net/manual/en/book.curl.php) or even [file_put_contents()](https://www.php.net/manual/en/function.file-put-contents.php) for the scope).
2. Wait until I release v3.5 or temporarly use the master branch (it's always bugs free) and write your own implementation of `File` interface, that will deal with remote files.

You can even go for the first solution until v3.5 is released to then switch to the second one.
