### ISSUE TITLE
Bytes Exhausted

### ISSUE THREAD

**Issue by Tufail-uet** [gasparesganga/php-shapefile#42]
When I try to read a large shapefile it gives me the following error.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes).

Is there any solution for it?

**Comment by gasparesganga** [comment]
The issue is **NOT** related to a large shapefile, as the library handles *one* record/geometry at time.
What is causing the issue is rather a large *geometry*, probably a polygon with thousands of vertices.

To fix it simply allow your script more memory increasing the value of [memory_limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit)

**Comment by Tufail-uet** [comment]
Yes it was **memory** issue. 
Increasing the memory limit from php.ini also did not solve my problem as many of the polygons have thousands of vertices. So I simply split the shapefiles and it worked.
Thanks for your response.
