### ISSUE TITLE
Error in ReadShapefile when reading a MultiPolygonZ shapefile 

### ISSUE THREAD

**Issue by sjafroudi** [gasparesganga/php-shapefile#45]
Hello,

I am trying to import [this](https://www.aec.gov.au/Electorates/gis/files/2021-Cwlth_electoral_boundaries_ESRI.zip) shapefile from [this](https://www.aec.gov.au/electorates/gis/gis_datadownload.htm) source and I get the following error in ShapefileReader:

```
Wrong record shape type in /var/www/vendor/gasparesganga/php-shapefile/src/Shapefile/ShapefileReader.php line 457 
```

Any insights on this error would be appreciated. Thank you!

**Comment by gasparesganga** [comment]
Hi!
I've just successfully opened and read the whole shapefile (151 records/geometries) you linked, using my library. I could not reproduce the issue.
What version of this library are you using?
Are you sure you linked to the same shapefile it is causing the issue?

By the way, that error description you pasted here should be the the message for a `ShapefileException` of type `Shapefile::ERR_SHP_WRONG_RECORD_TYPE`. Are you catching it?
That `ShapefileException` would provide more insights about the error (ie: *what record type*), which in any case would be related to bad or corrupted data.


Some considerations after reading the shapefile:
- This shapefile has some huge polygons/multipolygons (I mean, with an **extremely** large number of vertices) that may cause some memory issues to PHP in case you have a low `memory_limit` value set. But this should trigger an `Allowed memory size of exhausted` PHP Fatal error, so it's not the issue you are experiencing.
- I would set the `Shapefile::OPTION_FORCE_MULTIPART_GEOMETRIE`S constructor option to `true`, becuase there is a mix of polygons/multipolygons in the same shapefile. ESRI specs do not make any distintion between them, but usually GIS sofwtare and databases do.
- I would set the `Shapefile::OPTION_SUPPRESS_Z` and `Shapefile::OPTION_SUPPRESS_M` constructor option to `true` as well, because those value are always set to `0` for all the geometries in the shapefile.

**Comment by sjafroudi** [comment]
Thank you for your response! I'm a bit stuck trying to implement the second of your considerations. 

My approach so far has been to insert this line in the ShapefileReader constructor:

```
$this->getOption(Shapefile::OPTION_FORCE_MULTIPART_GEOMETRIES) = true;
```

Does that seem right?

**Comment by gasparesganga** [comment]
Actually, it does not! :)
Why are you trying to modify the library code? Believe me, all the advices I gave you are easily implementable in your code, using the library as it was intended. Think about the library as a *black box* that provides the desired functionality. In case it needed any fix or new feature, I would add it. But this is not the case, you can simply make a couple of adjustments to your code and you will be able to read those shapefiles.

Have you read the documentation? [Here you will find how setting constructor options](https://gasparesganga.com/labs/php-shapefile/#shapefilereader__construct ).

Anyways, here you are the correct way to set those constructor options:
```php
$ShapefileReader = new ShapefileReader('/path/to/your/shape.shp', [
    Shapefile::OPTION_FORCE_MULTIPART_GEOMETRIES    => true,
    Shapefile::OPTION_SUPPRESS_Z                    => true,
    Shapefile::OPTION_SUPPRESS_M                    => true,
]);
```

To increase the memory limit you can either use `ini_set('memory_limit', '500M');` at the beginning of your script, or even better `php_value memory_limit 500M` in an *.htaccess* file, or directly changing your php.ini (*not recommendedfor such a value!*).

And don't forget to catch `ShapefileException` exceptions! They will give you some great insights about possible issues with your shapefiles.

**Comment by sjafroudi** [comment]
Turns out it was a memory issue. Thanks for your help!
