### ISSUE TITLE
Tentative return types / dropping PHP 5 support?

### ISSUE THREAD

**Issue by Pascal-So** [gasparesganga/php-shapefile#46]
To ensure compatibility with future PHP versions, return type annotations will have to be added to the methods in `ShapefileReader` that implement the Iterator interface. This is because the built-in interfaces in PHP 8.1 now have return type annotations and omitting these type annotations on the implementations is deprecated and likely to be completely invalid in PHP 9. For more details see https://php.watch/versions/8.1/internal-method-return-types as they do a better job at explaining this.

For now this can be solved with the workaround attributes suggested in the linked article, but for PHP 9 we'll have to add the type annotations and thus make the library incompatible with PHP 5. If you're open to accept a PR on this then I'd be happy to go through and fix all the deprecation warnings, I just wanted to hear your opinion first if you'd prefer to drop PHP 5 support now already (has been EOL since 2018), or to add the attributes for now and then deal with it later. I'd be in favour of directly adding the type annotations now.

What's your opinion on this?

**Comment by gasparesganga** [comment]
Thank you for the feedback and proposed solutions.
I had been thinking about dropping PHP 5 support for some time, but ultimately decided to leave it for a simple reason: there are some users who supported this library in the past that are still on CentOS 7 and a fully security patched version of PHP 5 and I did not want to remove the support until it would become absolutely necessary.

I have been holding a couple of new features (one of which has already been committed more than one year ago!) but for various reasons I have never released them yet.
It's been a long time since the last bugfix release and this makes me positive about the fact that there aren't any, or at least not any that is affecting the current user base. This means that times has come to move forward with new features, while leaving some reliable legacy version in the form of `v3.4` for people who need to support older versions of PHP.

I think the best approach would be calling `v3.4.x` the *final PHP5/7-compatible release* and switching to a new v4 branch, where all new features will be implemented, including the ones I have beed holding.
In order to do that, I will need some time (a few weeks, probably a couple of months considering my current working schedule) to refactor the code and *bring it to the new century*: not having to support PHP5 means many things can be rewritten in a definitely more elegant way than the way they are now...

In the meantime, following your idea, I will release a v3.4.1 version that includes the `#[\ReturnTypeWillChange] ` attribute, but I will need to do it myself, stripping new features first from current codebase (not yet committed). It will be trivial so I suppose in the next few days I will be able to do that, no problem!
