### ISSUE TITLE
Generate new shapefile from geojson 

### ISSUE THREAD

**Issue by hamzaEssaadi** [gasparesganga/php-shapefile#55]
I have a geojson data and I want to create a new shapefile from that geojson , i think this great library is designed for write or read existing shapefiles,

**Comment by gasparesganga** [comment]
What kind of *issue* is this? You didn't even provided any message apart from the subject...
For these kind of questions you can use the comments section in the official [documentation ](https://gasparesganga.com/labs/php-shapefile/) page, ask a question on StackOverflow or even send me an email if you prefer.

Anyways, since your request is pretty generic, the only thing I can suggest is looking into [Geometry::initFromGeoJSON](https://gasparesganga.com/labs/php-shapefile/#geometryinitfromgeojson) method. It accepts any valid GeoJSON to initialize a Geometry object.

**Comment by hamzaEssaadi** [comment]
Thank you for your response ,I am sorry for this quick question, I was in a hurry , anyway I just updated the issue

**Comment by gasparesganga** [comment]
No problem, I didn't mean to be rude or something, but in order to help, one needs some details ;)

About your question, I think my answer is still valid: you are looking for creating a new shapefile using `ShapefileWriter` class and adding geometries to it using `Geometry::initFromGeoJSON()` method. The second example at the very beginning of the official documentation ([Writing Shapefiles](https://gasparesganga.com/labs/php-shapefile/#writing-shapefiles)) should give you a good idea on how to use that class.

If you have any issue with some code you wrote that it does not work as expected, feel free to post it here and I will look into it.

**Comment by hamzaEssaadi** [comment]
Thank you so much , ll look again on the documentation to achieve that ,
