### ISSUE TITLE
Error Type: ERR_FILE_EXISTS Message: Check if the file exists and is readable and/or writable Details: demo.shx

### ISSUE THREAD

**Issue by jlai79** [gasparesganga/php-shapefile#57]
When I try to read a shp file like this:

`$Shapefile = new ShapefileReader("demo.shp");`

I get this error massage:

```
Error Type: ERR_FILE_EXISTS 
Message: Check if the file exists and is readable and/or writable 
Details: demo.shx
```

I don't have an shx file, only the shp.

The shp file exists and also with the full path to the shp file the same error occurs.

Am I doing something wrong? How can I fix this issue?

**Comment by gasparesganga** [comment]
I think it's very clear what's happening, since you wrote it yourself:

> I don't have an shx file, only the shp.

The error is telling you exactly that: the SHX file does not exist :)

In this case you can use the `Shapefile::OPTION_IGNORE_FILE_SHX` as explained in trhe documentation for [ShapefileReader::__construct](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilereader):

```php
$Shapefile = new ShapefileReader('demo.shp', [
    Shapefile::OPTION_IGNORE_FILE_SHX => true,
]);
```
Keep in mind that you will loose the ability to perform random access to records this way *(ie: you won't be able to use `ShapefileReader::setCurrentRecord()` and `Shapefile::getTotRecords` methods)* and in some very special cases when a shapefile is *weird* the library could be unable to read it.

Of course the same applies to the DBF file. In case you don't have it, use the `Shapefile::OPTION_IGNORE_FILE_DBF` constructor option:

```php
$Shapefile = new ShapefileReader("demo.shp", [
    Shapefile::OPTION_IGNORE_FILE_DBF => true,
    Shapefile::OPTION_IGNORE_FILE_SHX => true,
]);
```

By the way, the **best** way to *fix the issue* would be having the 3 fundamental files that compose a shapefile: SHP, SHX and DBF...

**Comment by jlai79** [comment]
Thanks for your quick reply and the explanation. I changed my code to also use dbf and shx files and now it works again.

I have used this library in different versions since 2016 without dbf and shx files. Today I integrated this library in a new project the same way I did before and got this error. Very strange. Thanks a lot once more.

**Comment by gasparesganga** [comment]
Thank you ;)

**Comment by camilamoreiradev** [comment]
I had the same problem and I didn't know that it was correct to use the 3 files for correct operation. His explanation was sensational.
