### ISSUE TITLE
Corrupt shapefiles plague, and what to expect when dealing with them

### ISSUE THREAD

**Issue by thalisvilela** [gasparesganga/php-shapefile#59]
I'm aware of the issues discussed in #49 and #38 , and i'm really baffled to find these corrupt files comming from "huge companies". My question is: There are any plans to parse this corrupt files ignoring this seamingly omnipresent errors?
I'll include two files that i fail to parse using php-shapefile, but open without any issues in  QGIS  version | 3.22.4-Białowieża on Ubuntu.
[AUR01.shp](https://umobi.com.br/AUR01.shp) and [AUR04.shp](https://umobi.com.br/AUR04.shp)

I'm greeted by the type error if i supress PHP warnings:
`TypeError {
  #message: "current(): Argument #1 ($array) must be of type array, bool given"
  #code: 0
  #file: ".../gasparesganga/php-shapefile/src/Shapefile/ShapefileReader.php"
  #line: 317
}`

And by the Exception if i dont supress PHP warnings: 
`ErrorException {
  #message: "unpack(): Type d: not enough input, need 8, have 0"
  #code: 0
  #file: ".../gasparesganga/php-shapefile/src/Shapefile/ShapefileReader.php"
  #line: 317
  #severity: E_WARNING
}`

But in QGIS, they look alright...
![qgis_layers](https://github.com/gasparesganga/php-shapefile/assets/1225277/28479d88-0780-4c04-9ac4-05b42fc4780c)

**Comment by thalisvilela** [comment]
PS: I have some files that even QGIS won't open, but the "company" says they're opening them just fine in their software (i'm trying to figure out what software that is).

**Comment by gasparesganga** [comment]
Hi!
To be honest, I am more baffled than you are, really!

As you suggested, those shapefiles are corrupted, but not just regarding M and Z dimensions, they are missing some more bytes as well. I have no idea about what software could possibly produce them, but I am starting to think there must be some kind of library used by more than one desktop software that got it wrong. ESRI specs are clear and have been the same for 25 years, why changing a file format that is used for its *interoperability*?

Anyways, you can try using the same code I proposed in #38 but try also to add a few useless bytes at the end of the SHP file **before** running that code. Something like that:
```php
$fh = fopen($input_fille, 'c+b');
fseek($fh, 0, SEEK_END);
fwrite($fh, pack('A*', implode('', array_fill(0, 512, '0'))));
fclose($fh);
```

By the way, that code would produce a `Polygon` Shapefile, which is what it seems you actually need. All those corrupted shapefiles share the same trait: they are `PolygonZ` but both Z and M dimensions are not used.
Another try would be exporting the shapefile directly as 2D `Polygon`, it shouldn't have any missing bytes.

I will try to include some mechanism to seamlessly recover this kind of shapefiles in next releases, but it's not as easy as it sounds, I don't wanna promote any data loss nor bad practiced with corrupted shapefiles. In an ideal world, that faulty software producing corrupted shapefiles should be fixed in the first place!

**Comment by thalisvilela** [comment]
I'm so frustrated, any effort to solve out of spec files seems so wrong. Yet, this files are popping out from several different sources.  I'll try and pinpoint the software they're using, and maybe confirm the common broken library hypothesis, and in the mean time, implement some fallback code to maybe recover some of this files. Thank you very much for the quick and helpfull reply!

**Comment by gasparesganga** [comment]
No problem! Should you need any further assistance, do not hesitate to get back to me.
Also, if you discover anything about that suspicious software that produces corrupted files, please let me know. I will definitely try my best to handle the situation within the library.

Cheers!

**Comment by thalisvilela** [comment]
I'll definitely come back to report any finding. 
By the way, adding bytes to the end of the file solved the problem for the particular examples i shared. 
Thank you again!
