### ISSUE TITLE
Force cast geometry to multi geometry

### ISSUE THREAD

**Issue by fulf** [gasparesganga/php-shapefile#9]
Considering the fact that getShapeType(ShapeFile::FORMAT_STR) doesn't differentiate between simple geometry and multi geometry, and the shp property is inconsistent when returning WKT (sometimes displaying GEOMETRY, sometimes MULTIGEOMETRY) can you implement a flag when either opening the shapefile or when getting records to forcecast the WKT geometry to multigeometry?

**Comment by gasparesganga** [comment]
The problem lies in the ESRI Shapefile format itself, have a look at the [specs](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf): there are no _MultiPolyline_ or _MultiPolygon_ but only _Polyline_ and _Polygon_.
Don't ask me why (especially since _MultiPoint_ is there), that was an odd choice on ESRI side.
The consequence is that _MultiPolyline_ and _MultiPolygon_ are just _Polyline_ and _Polygon_ according to the specs, thus it's not possible to determine beforehand the contents of a Shapefile. Even worse, **a Shapefile can contain both _single_ and _multi_ geometries!**

This situation is handled differently across various GIS softwares. Some of them cast the multi geometries correctly, others produce single _Linestrings_ and _Polygons_ which are _not valid_ according to the OGC's definition.

**My approach was to detect the mult-geometries and always produce some valid output, being either a structured array _(in which multi-geometries parts are defined)_ or well-formed WKT.**

You can check the geometries right after you read them: if you are using WKT output then check if it starts with `"MULTI"`, or, in case of array output, you can check number of `parts` in the returned array.

As for subsequent processing of the WKT, for example in PostGIS I usually input all the geometries forcing them to _multi_ with something like `ST_Multi(ST_GeomFromText('---wkt here---'))`, then I check if **all** of them are actually _single_ geometries and eventually transform them back using `ST_Dump()`.
Even if only one geometry out of a million is _multi_, then all of them will remain as such. Don't forget that a _single_ geometry is also perfectly valid as _multi_.
This way I am sure to have homogeneous geometry types in my tables.

**Comment by gasparesganga** [comment]
A couple of weeks with no answer, I assume my solution was ok, or you have found another one.
I'm closing this, cheers.
